### ISSUE TITLE
Missing nginx-module-graphite-1.25.1+4.3 after two weeks from 1.25.1 release

### ISSUE THREAD

**Issue by iamstarkov** [GetPageSpeed/nginx-extras#17]
> Changes with nginx 1.25.1      13 Jun 2023
> — https://nginx.org/en/CHANGES, https://nginx.org/en/download.html

And there are no builds for 1.25.1
https://extras.getpagespeed.com/redhat/7/x86_64/repoview/nginx-module-graphite.html

I know its mainline, but NGINX recommends to use it unless you have problems:

> We recommend that in general you deploy the NGINX mainline branch at all times.
> — https://www.nginx.com/blog/nginx-1-6-1-7-released/

**Comment by dvershinin** [comment]
Available in the mainline repository at https://extras.getpagespeed.com/redhat/7/mainline/x86_64/repoview/nginx-module-graphite.html
