### ISSUE TITLE
Authentication with active directory backend for upstreams 

### ISSUE THREAD

**Issue by indra281** [GetPageSpeed/nginx-extras#6]
I there any alternative for the ntlm module, I have backend windows AD for authentication with the web app. is there any way i can change in vhosts or the upstreams to solve this problem 
thanks :)

**Comment by dvershinin** [comment]
@indra281 if you can find the module to do the job, it can be added. If not, then not :) As simple as that. When you find one, you can mention it here. The nginx-extras include virtually 90% of all NGINX modules available in GitHub.
