### ISSUE TITLE
Nginx modsecirity error

### ISSUE THREAD

**Issue by indra281** [GetPageSpeed/nginx-extras#7]
Hi 
I subscribed getpagespeed and configured in my prod. it was working good.
yesterday I rebuild my Nginx server and configured the same was like last time did but worker process is getting restart automatically.

error log in /var/log/nginx/error.log

2019/10/20 09:23:46 [alert] 18941#18941: worker process 18943 exited on signal 11
2019/10/20 09:23:46 [notice] 18941#18941: start worker process 19369
2019/10/20 09:23:46 [notice] 18941#18941: signal 29 (SIGIO) received
2019/10/20 09:23:48 [notice] 18941#18941: signal 17 (SIGCHLD) received from 19368
2019/10/20 09:23:48 [alert] 18941#18941: worker process 19368 exited on signal 11
2019/10/20 09:23:48 [notice] 18941#18941: start worker process 19381
2019/10/20 09:23:48 [notice] 18941#18941: signal 29 (SIGIO) received
2019/10/20 09:23:55 [notice] 18941#18941: signal 17 (SIGCHLD) received from 19369
2019/10/20 09:23:55 [alert] 18941#18941: worker process 19369 exited on signal 11
2019/10/20 09:23:55 [notice] 18941#18941: start worker process 19393
2019/10/20 09:23:55 [notice] 18941#18941: signal 29 (SIGIO) received

error log in /var/log/message

Oct 20 09:13:10 qrznginxlb5071a kernel: nginx[17580]: segfault at 28 ip 00007fe45e5f7ba4 sp 00007ffc942c6cf0 error 4 in libmodsecurity.so.3.0.2[7fe45e4da000+1ff000]

Please have  a look as this is a production server

**Comment by dvershinin** [comment]
Hi,

Please check if `libmodsecurity` package is recent enough. 

`repoquery -l libmodsecurity` gives:

```
/usr/bin/modsec-rules-check
/usr/lib64/libmodsecurity.so.3
/usr/lib64/libmodsecurity.so.3.0.3
/usr/share/doc/libmodsecurity-3.0.3
/usr/share/doc/libmodsecurity-3.0.3/AUTHORS
/usr/share/doc/libmodsecurity-3.0.3/README.md
/usr/share/licenses/libmodsecurity-3.0.3
/usr/share/licenses/libmodsecurity-3.0.3/LICENSE
```
In your log you're using `libmodsecurity.so.3.0.2` so it's not recent and most likely installed from EPEL repository. So simply try `yum update libmodsecurity` when GetPageSpeed repository is enabled and ensure you're on the version that is not EPEL one.

**Comment by dvershinin** [comment]
@indra281 Since I haven't heard from you about it, I believe this is safe to close.
