### ISSUE TITLE
You say it's freeware, but I get error, and getpagespeed-extras website says there's a monthly fee

### ISSUE THREAD

**Issue by jamminjames** [GetPageSpeed/nginx-extras#8]
After installing and enabling getpagespeed-extras, when I try to install anything (like nginx-module-cache-purge), I get an error, which includes this:

"Error importing repomd.xml for getpagespeed-extras-mainline: Damaged repomd.xml file"

Researching, this page says it costs $10/month to get it working (https://www.getpagespeed.com/repo-subscribe). Is it only available by subscription this way? Or how can I fix the issue?

Thanks!

**Comment by dvershinin** [comment]
Hi, I have replied [here](https://github.com/FRiCKLE/ngx_cache_purge/issues/63). Updated README here to mention it's not free.

Just for some historical background: it has been free for years, however not a single soul donated although have been in use by thousands of servers worldwide. The subscription module was introduced this year to cover at least hosting costs.

**Comment by Publimix** [comment]
> Just for some historical background: it has been free for years, however, not a single soul donated although it has been in use by thousands of servers worldwide. The subscription model was introduced this year to cover at least hosting costs.

Hi Danila! I totally agree with you introducing paid subscriptions since anyone cares about your effort. But, I you can accept my remark, the subscription cost is not transparent. I would state clearly the price of the services, if I were you. Now, it looks very shady how it is presented and I would hesitate to go all in...
Have a great day!

**Comment by dvershinin** [comment]
@Publimix and I actually agree it's shady but haven't found another "good" option than just showing it up on the PayPal page, so I don't have to hardcode the price on many pages, and it's pretty dynamic as I still can't find the best price that suits everyone!

That said, the Fedora repositories (new from this year) are free and not subject to subscription.  Please see [free repository usage](https://www.getpagespeed.com/free-rpm-repository-usage).

**Comment by wallyreport** [comment]
Seems to me: IBM / Redhat should pay for this. If IBM is going to charge for Linux, then they should pay for any need repositories.
